apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: networkmap
  annotations:
    flux.weave.works/automated: "false"
  namespace: supplychain-ns
spec:
  releaseName: networkmap
  chart:
    path: platforms/r3-corda/charts/nms-tls
    git: git@github.com:tamilacc/blockchain-automation-framework.git
    ref: develop
  values:
    nodeName: networkmap
    metadata:
      namespace: supplychain-ns
    image:
      authusername: sa
      containerName: index.docker.io/hyperledgerlabs/networkmap-linuxkit:latest
      env:
      - name: NETWORKMAP_PORT
        value: 8080
      - name: NETWORKMAP_ROOT_CA_NAME
        value: CN=Network Map,OU=FRA,O=FRA,L=Berlin,C=DE
      - name: NETWORKMAP_TLS
        value: true
      - name: NETWORKMAP_DB
        value: /opt/networkmap/db
      - name: DB_USERNAME
        value: networkmap
      - name: NETWORKMAP_AUTH_USERNAME
        value: sa
      - name: DB_URL
        value: mongodb-networkmap
      - name: DB_PORT
        value: 27017
      - name: DATABASE
        value: admin
      - name: NETWORKMAP_CACHE_TIMEOUT
        value: 60S
      - name: NETWORKMAP_MONGOD_DATABASE
        value: networkmap
      imagePullSecret: regcred
      tlsCertificate: true
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      mountPath:
          basePath: /opt/networkmap
    storage:
      memory: 512Mi
      mountPath: "/opt/h2-data"
      name: awsstorageclass
    vault:
      address: http://a93f4d214c79f11eabd1f0a9dae90b0e-1191321496.eu-west-3.elb.amazonaws.com:9000
      role: vault-role
      authpath: cordanetworkmap
      serviceaccountname: vault-auth
      secretprefix: networkmap
      certsecretprefix: networkmap/certs
      dbcredsecretprefix: networkmap/credentials/mongodb
      secretnetworkmappass: networkmap/credentials/userpassword
      tlscertsecretprefix: networkmap/tlscerts
      dbcertsecretprefix: networkmap/certs
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
      dburl: mongodb-networkmap:27017
    service:
      port: 8080
      targetPort: 8080
      type: ClusterIP
      annotations: {}
    deployment:
      annotations: {}
    pvc:
      annotations: {}
    ambassador:
      external_url_suffix: cor.cluster01.aws.bafevent.com
      