apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: manufacturer
  annotations:
    flux.weave.works/automated: "false"
  namespace: manufacturer-ns
spec:
  releaseName: manufacturer
  chart:
    path: platforms/r3-corda/charts/node
    git: git@github.com:tamilacc/blockchain-automation-framework.git
    ref: develop
  values:
    nodeName: manufacturer
    replicas: 1
    metadata:
      namespace: manufacturer-ns
    image:
      containerName: index.docker.io/hyperledgerlabs/corda:4.1-linuxkit
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: doorman.cor.cluster01.aws.bafevent.com
      networkmapCertAlias: networkmap.cor.cluster01.aws.bafevent.com
    nodeConf:
      p2p:
        url: manufacturer.manufacturer-ns
        port: 10002
      ambassadorAddress: manufacturer.cor.cluster01.aws.bafevent.com:10020
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
      attachmentCacheBound: 1024
       
      detectPublicIp: false
      database:
        transactionIsolationLevel: READ_COMMITTED
        exportHibernateJMXStatistics: false
      dbUrl: manufacturerdb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://manufacturerdb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: https://networkmap.cor.cluster01.aws.bafevent.com:8443
      doormanURL: https://doorman.cor.cluster01.aws.bafevent.com:8443
      compatibilityZoneURL:
      jarVersion: 4.1
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: manufactureroperations
          permissions: [ALL]

    cordapps:
      getcordapps: false

    volume:
      baseDir: /base/corda
    resources:
      limits: "1Gi"
      requests: "1Gi" 
    pvc:
      name: manufacturer-pvc
      annotations: {}
      memory: 512Mi
      storageClassName: awsstorageclass

    service:
      name: manufacturer
      type: ClusterIP
      p2p:
        port: 10002
        targetPort: 10002
      rpc:
        port: 10003
        targetPort: 10003 
      rpcadmin:
        port: 10005
        targetPort: 10005
         
    deployment:
      annotations: {}
    vault:
      address: http://a93f4d214c79f11eabd1f0a9dae90b0e-1191321496.eu-west-3.elb.amazonaws.com:9000
      role: vault-role
      authpath: cordamanufacturer
      serviceaccountname: vault-auth
      dbsecretprefix: manufacturer/credentials/database
      rpcusersecretprefix: manufacturer/credentials/rpcusers
      tokensecretprefix: manufacturer/credentials/vaultroottoken
      keystoresecretprefix: manufacturer/credentials/keystore
      certsecretprefix: manufacturer/certs
      networkmapsecretprefix: manufacturer/credentials/networkmappassword
      cordappsreposecretprefix: manufacturer/credentials/cordapps

          
    healthcheck:
      readinesscheckinterval: 20
      readinessthreshold: 20
    ambassador:
      component_name: manufacturer
      external_url_suffix: cor.cluster01.aws.bafevent.com
      p2p_ambassador: 10020
      
