apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: store
  annotations:
    flux.weave.works/automated: "false"
  namespace: store-ns
spec:
  releaseName: store
  chart:
    path: platforms/r3-corda/charts/node
    git: git@github.com:tamilacc/blockchain-automation-framework.git
    ref: develop
  values:
    nodeName: store
    replicas: 1
    metadata:
      namespace: store-ns
    image:
      containerName: index.docker.io/hyperledgerlabs/corda:4.1-linuxkit
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: doorman.cor.cluster01.aws.bafevent.com
      networkmapCertAlias: networkmap.cor.cluster01.aws.bafevent.com
    nodeConf:
      p2p:
        url: store.store-ns
        port: 10002
      ambassadorAddress: store.cor.cluster01.aws.bafevent.com:10040
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: O=Store,OU=Store,L=40.73/-74/New York,C=US #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
      attachmentCacheBound: 1024
       
      detectPublicIp: false
      database:
        transactionIsolationLevel: READ_COMMITTED
        exportHibernateJMXStatistics: false
      dbUrl: storedb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://storedb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: https://networkmap.cor.cluster01.aws.bafevent.com:8443
      doormanURL: https://doorman.cor.cluster01.aws.bafevent.com:8443
      compatibilityZoneURL:
      jarVersion: 4.1
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: storeoperations
          permissions: [ALL]

    cordapps:
      getcordapps: true
      jars:
        - url: 
        - url: 
        
    volume:
      baseDir: /base/corda
    resources:
      limits: "1Gi"
      requests: "1Gi" 
    pvc:
      name: store-pvc
      annotations: {}
      memory: 512Mi
      storageClassName: awsstorageclass

    service:
      name: store
      type: ClusterIP
      p2p:
        port: 10002
        targetPort: 10002
      rpc:
        port: 10003
        targetPort: 10003 
      rpcadmin:
        port: 10005
        targetPort: 10005
         
    deployment:
      annotations: {}
    vault:
      address: http://a93f4d214c79f11eabd1f0a9dae90b0e-1191321496.eu-west-3.elb.amazonaws.com:9000
      role: vault-role
      authpath: cordastore
      serviceaccountname: vault-auth
      dbsecretprefix: store/credentials/database
      rpcusersecretprefix: store/credentials/rpcusers
      tokensecretprefix: store/credentials/vaultroottoken
      keystoresecretprefix: store/credentials/keystore
      certsecretprefix: store/certs
      networkmapsecretprefix: store/credentials/networkmappassword
      cordappsreposecretprefix: store/credentials/cordapps

          
    healthcheck:
      readinesscheckinterval: 20
      readinessthreshold: 20
    ambassador:
      component_name: store
      external_url_suffix: cor.cluster01.aws.bafevent.com
      p2p_ambassador: 10040
      
